<?php

namespace Database\Seeders;
use App\Models\Products;
use Illuminate\Database\Seeder;

class ProductsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $dat =  [
            // BOTTLE SERVIES
            [
                'name' =>'Carlo Rossie Red',
                'category_id' => 2,
                'stock' =>0,
                'price' =>10000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Carlo Rossie White',
                'category_id' => 2,
                'stock' =>0,
                'price' =>10000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Martel Swift',
                'category_id' => 2,
                'stock' =>0,
                'price' =>80000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Jameson Normal',
                'category_id' => 2,
                'stock' =>0,
                'price' =>20000,
                'out_of_stock' =>0,
                'code' =>null,
            ],

            [
                'name' =>'Jameson Black',
                'category_id' => 2,
                'stock' =>0,
                'price' =>35000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Hennessey VS',
                'category_id' => 2,
                'stock' =>0,
                'price' =>60000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Hennessey VSOP',
                'category_id' => 2,
                'stock' =>0,
                'price' =>80000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Black Label',
                'category_id' => 2,
                'stock' =>0,
                'price' =>30000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Glenfidich 12 Years',
                'category_id' => 2,
                'stock' =>0,
                'price' =>45000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Glenfidich 15 Years',
                'category_id' => 2,
                'stock' =>0,
                'price' =>60000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Glenfidich 18 Years',
                'category_id' => 2,
                'stock' =>0,
                'price' =>90000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Four Cousins',
                'category_id' => 2,
                'stock' =>0,
                'price' =>10000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Baileys',
                'category_id' => 2,
                'stock' =>0,
                'price' =>15000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            
            // FOOD
            [
                'name' =>'Prawns in Chilli Sauce',
                'category_id' =>1,
                'stock' =>0,
                'price' =>6000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Hot and Sour',
                'category_id' =>1,
                'stock' =>0,
                'price' =>6000,
                'out_of_stock' =>0,
                'code' =>null,
            ],

            [
                'name' =>'Bijou Special Rice',
                'category_id' =>1,
                'stock' =>0,
                'price' =>5500,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Beef Fried Rice',
                'category_id' =>1,
                'stock' =>0,
                'price' =>5000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Seafood Special Frid Rice',
                'category_id' =>1,
                'stock' =>0,
                'price' =>6500,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Jollof Rice',
                'category_id' =>1,
                'stock' =>0,
                'price' =>4000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Egg Fried Rice',
                'category_id' =>1,
                'stock' =>0,
                'price' =>2000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Steamed Rice',
                'category_id' =>1,
                'stock' =>0,
                'price' =>1500,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Bijou Special Noodle',
                'category_id' =>1,
                'stock' =>0,
                'price' =>5000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Beef Ramen',
                'category_id' =>1,
                'stock' =>0,
                'price' =>4000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'English Breakfast',
                'category_id' =>1,
                'stock' =>0,
                'price' =>5500,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'American Breakfast',
                'category_id' =>1,
                'stock' =>0,
                'price' =>5500,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Nigerian Breakfast',
                'category_id' =>1,
                'stock' =>0,
                'price' =>4000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Chicken Hot Plate',
                'category_id' =>1,
                'stock' =>0,
                'price' =>5000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Beef Hot Plate',
                'category_id' =>1,
                'stock' =>0,
                'price' =>5000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Fish Hot Plate',
                'category_id' =>1,
                'stock' =>0,
                'price' =>6000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Prawns Hot Plate',
                'category_id' =>1,
                'stock' =>0,
                'price' =>6000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Chicken in Sighuan Sauce',
                'category_id' =>1,
                'stock' =>0,
                'price' =>5000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Quarter Chicken',
                'category_id' =>1,
                'stock' =>0,
                'price' =>3500,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Half Chicken',
                'category_id' =>1,
                'stock' =>0,
                'price' =>7000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Whole Chicken',
                'category_id' =>1,
                'stock' =>0,
                'price' =>14000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Grilled Cat Fish',
                'category_id' =>1,
                'stock' =>0,
                'price' =>6000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Grilled Croacker Fish',
                'category_id' =>1,
                'stock' =>0,
                'price' =>6000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Grilled Tilapia Fish',
                'category_id' =>1,
                'stock' =>0,
                'price' =>6000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Chicken Strips',
                'category_id' =>1,
                'stock' =>0,
                'price' =>4000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Butterfly Prawns',
                'category_id' =>1,
                'stock' =>0,
                'price' =>6000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Deep Fried Calamari',
                'category_id' =>1,
                'stock' =>0,
                'price' =>5000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Wings 6pcs',
                'category_id' =>1,
                'stock' =>0,
                'price' =>3500,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            // mocktails and smoothies
            [
                'name' =>'Pina Colada',
                'category_id' =>3,
                'stock' =>0,
                'price' =>4000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Virgin Mojito',
                'category_id' =>3,
                'stock' =>0,
                'price' =>5000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Blue Lagoon',
                'category_id' =>3,
                'stock' =>0,
                'price' =>4000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Moscow Mule',
                'category_id' =>3,
                'stock' =>0,
                'price' =>4500,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Juicy Julep',
                'category_id' =>3,
                'stock' =>0,
                'price' =>5000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Sparkling Pineapple',
                'category_id' =>3,
                'stock' =>0,
                'price' =>4000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Bijou',
                'category_id' =>3,
                'stock' =>0,
                'price' =>5000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Banana and Stawberry',
                'category_id' =>3,
                'stock' =>0,
                'price' =>2500,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Pineapple and Ginger',
                'category_id' =>3,
                'stock' =>0,
                'price' =>2500,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Tropical Blend',
                'category_id' =>3,
                'stock' =>0,
                'price' =>2500,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Paradise Smoothie',
                'category_id' =>3,
                'stock' =>0,
                'price' =>2500,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Bijou Special',
                'category_id' =>3,
                'stock' =>0,
                'price' =>2500,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Orange Juice',
                'category_id' =>3,
                'stock' =>0,
                'price' =>1500,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Pineapple Juice',
                'category_id' =>3,
                'stock' =>0,
                'price' =>1500,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Water Melon Juice',
                'category_id' =>3,
                'stock' =>0,
                'price' =>1500,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Mixed Fruit',
                'category_id' =>3,
                'stock' =>0,
                'price' =>2000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            
            [
                'name' =>'Vanilla Shakes',
                'category_id' =>3,
                'stock' =>0,
                'price' =>3000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            
            [
                'name' =>'Oreo Shakes',
                'category_id' =>3,
                'stock' =>0,
                'price' =>3500,
                'out_of_stock' =>0,
                'code' =>null,
            ],

            
            [
                'name' =>'Strawberry and Cream',
                'category_id' =>3,
                'stock' =>0,
                'price' =>3000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            
            [
                'name' =>'Banana Shakes',
                'category_id' =>3,
                'stock' =>0,
                'price' =>3000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Chocolate Banana Shakes',
                'category_id' =>3,
                'stock' =>0,
                'price' =>3000,
                'out_of_stock' =>0,
                'code' =>null,
            ],

            [
                'name' =>'Caramel Shakes',
                'category_id' =>3,
                'stock' =>0,
                'price' =>3000,
                'out_of_stock' =>0,
                'code' =>null,
            ],

            
            [
                'name' =>'Green Tea',
                'category_id' =>3,
                'stock' =>0,
                'price' =>1000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            
            [
                'name' =>'Black Tea',
                'category_id' =>3,
                'stock' =>0,
                'price' =>1000,
                'out_of_stock' =>0,
                'code' =>null,
            ],

            
            [
                'name' =>'Lemon Tea',
                'category_id' =>3,
                'stock' =>0,
                'price' =>1000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            
            [
                'name' =>'Morocan Tea',
                'category_id' =>3,
                'stock' =>0,
                'price' =>1000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Bijou Special',
                'category_id' =>3,
                'stock' =>0,
                'price' =>1500,
                'out_of_stock' =>0,
                'code' =>null,
            ],

            
            [
                'name' =>'Cappaccino Tea',
                'category_id' =>3,
                'stock' =>0,
                'price' =>1500,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            
            [
                'name' =>'caafe Latte',
                'category_id' =>3,
                'stock' =>0,
                'price' =>1500,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            
            [
                'name' =>'Expresso',
                'category_id' =>3,
                'stock' =>0,
                'price' =>1000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Cafe Americano',
                'category_id' =>3,
                'stock' =>0,
                'price' =>1000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Long Island',
                'category_id' =>4,
                'stock' =>0,
                'price' =>5000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            
            [
                'name' =>'Adios Motherfucker',
                'category_id' =>4,
                'stock' =>0,
                'price' =>5500,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            
            [
                'name' =>'Tequila Sunrise',
                'category_id' =>4,
                'stock' =>0,
                'price' =>4000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Strawberry Daquiri',
                'category_id' =>4,
                'stock' =>0,
                'price' =>5000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            
            [
                'name' =>'Whiskey Sour',
                'category_id' =>4,
                'stock' =>0,
                'price' =>6000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            
            [
                'name' =>'Ameretto Sour',
                'category_id' =>4,
                'stock' =>0,
                'price' =>6000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            
            [
                'name' =>'Bull Frog',
                'category_id' =>4,
                'stock' =>0,
                'price' =>6000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Medusa Snake Head',
                'category_id' =>4,
                'stock' =>0,
                'price' =>5000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Sex on the beach',
                'category_id' =>4,
                'stock' =>0,
                'price' =>5000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Cosmopolitan',
                'category_id' =>4,
                'stock' =>0,
                'price' =>4500,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Magarita',
                'category_id' =>4,
                'stock' =>0,
                'price' =>5000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Mai Tai',
                'category_id' =>4,
                'stock' =>0,
                'price' =>5000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Old Fashioned',
                'category_id' =>4,
                'stock' =>0,
                'price' =>4000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Mojito',
                'category_id' =>4,
                'stock' =>0,
                'price' =>5000,
                'out_of_stock' =>0,
                'code' =>null,
            ],


            // homeland down
            [
                'name' =>'Asun Party',
                'category_id' =>1,
                'stock' =>0,
                'price' =>4000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Goatmeatt Peppersoup',
                'category_id' =>1,
                'stock' =>0,
                'price' =>4000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Fish Peppersoup',
                'category_id' =>1,
                'stock' =>0,
                'price' =>6000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Nkwobi',
                'category_id' =>1,
                'stock' =>0,
                'price' =>5000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Shayo Platter',
                'category_id' =>1,
                'stock' =>0,
                'price' =>5000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Shayo Platter',
                'category_id' =>1,
                'stock' =>0,
                'price' =>5000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Peppered Goatmeat',
                'category_id' =>1,
                'stock' =>0,
                'price' =>4000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Peppered Gizzard',
                'category_id' =>1,
                'stock' =>0,
                'price' =>4000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Peppered Snail',
                'category_id' =>1,
                'stock' =>0,
                'price' =>7000,
                'out_of_stock' =>0,
                'code' =>null,
            ],

            [
                'name' =>'Small Chops Platter',
                'category_id' =>1,
                'stock' =>0,
                'price' =>10000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Wings Platter',
                'category_id' =>1,
                'stock' =>0,
                'price' =>12000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Mixed Platter',
                'category_id' =>1,
                'stock' =>0,
                'price' =>14000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Bijou Special Burger',
                'category_id' =>1,
                'stock' =>0,
                'price' =>5000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Classic Burger',
                'category_id' =>1,
                'stock' =>0,
                'price' =>3500,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Crispy Chicken Burger',
                'category_id' =>1,
                'stock' =>0,
                'price' =>4000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'BBQ Beef Burger',
                'category_id' =>1,
                'stock' =>0,
                'price' =>3800,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Philly Cheese Steak Sandwich',
                'category_id' =>1,
                'stock' =>0,
                'price' =>4500,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Steak Wrap',
                'category_id' =>1,
                'stock' =>0,
                'price' =>3500,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Chicken Wrap',
                'category_id' =>1,
                'stock' =>0,
                'price' =>3500,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Chicken Avocado Wrap',
                'category_id' =>1,
                'stock' =>0,
                'price' =>4000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Club Sandwich',
                'category_id' =>1,
                'stock' =>0,
                'price' =>4500,
                'out_of_stock' =>0,
                'code' =>null,
            ],

            [
                'name' =>'Alfredo Pasta',
                'category_id' =>1,
                'stock' =>0,
                'price' =>5000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            
            [
                'name' =>'Spaghetti Bolognese',
                'category_id' =>1,
                'stock' =>0,
                'price' =>5000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            
            [
                'name' =>'Seafood Pasta',
                'category_id' =>1,
                'stock' =>0,
                'price' =>6000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            
            [
                'name' =>'Spaghetti With Meatballs',
                'category_id' =>1,
                'stock' =>0,
                'price' =>6000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            
            [
                'name' =>'Spaghetti Jellof',
                'category_id' =>1,
                'stock' =>0,
                'price' =>5000,
                'out_of_stock' =>0,
                'code' =>null,
            ],

            [
                'name' =>'French Fries',
                'category_id' =>1,
                'stock' =>0,
                'price' =>1500,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Loaded Fries',
                'category_id' =>1,
                'stock' =>0,
                'price' =>3000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Yam Stick',
                'category_id' =>1,
                'stock' =>0,
                'price' =>2000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Sweet Potato Fries',
                'category_id' =>1,
                'stock' =>0,
                'price' =>2000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Sauteed Vegetables',
                'category_id' =>1,
                'stock' =>0,
                'price' =>2000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Plantain',
                'category_id' =>1,
                'stock' =>0,
                'price' =>2000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Sweet Potato Fries',
                'category_id' =>1,
                'stock' =>0,
                'price' =>2000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Bijou Fruit Mix',
                'category_id' =>1,
                'stock' =>0,
                'price' =>5000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            [
                'name' =>'Chocolate Mousse',
                'category_id' =>1,
                'stock' =>0,
                'price' =>5000,
                'out_of_stock' =>0,
                'code' =>null,
            ],
            
            
            
            
            
            
            
            
            
        ];

    for ($i=0; $i < count($dat) ; $i++) {
        $product = [
            'name' =>$dat[$i]['name'],
            'category_id' => $dat[$i]['category_id'],
            'stock' =>$dat[$i]['stock'],
            'price' =>$dat[$i]['price'],
            'out_of_stock' =>$dat[$i]['out_of_stock'],
            'code' =>$dat[$i]['code'],
        ];
        Products::create($product);
    }
    }
}
